spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      #ddl-auto: create #utilizado na primeira vez que roda em produção
       ddl-auto: validade


#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#   password: ${PGPASSWORD}
#  jpa:
#   open-in-view: false
#   hibernate:
#     ddl-auto: validade